services:
    animorank:
        image: animorank-client
        container_name: animorank-client
        build: 
            context: ./animorank-client
            dockerfile: Dockerfile
        user: node
        env_file:
            - ./animorank-client/.env
        restart: always
        ports:
            - 3000:3000
    piston:
        image: ghcr.io/engineer-man/piston
        container_name: piston
        restart: always
        ports:
            - 2000:2000
        volumes:
            - ./piston/data/piston/packages:/piston/packages
        tmpfs:
            - /piston/jobs
            - /tmp
    cloudflared:
        image: cloudflare/cloudflared:latest
        container_name: cloudflared
        restart: always
        command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN} 
        
